# Menggunakan base image yang sesuai untuk aplikasi Java
FROM openjdk:17-jre-slim
  
  # Menyalin file JAR dari host ke dalam container
COPY target/crud-nasabah.jar /app/crud-nasabah-app.jar
  
  # Menentukan direktori kerja di dalam container
WORKDIR /app
  
  # Menjalankan aplikasi Java saat container dimulai
CMD ["java", "-jar", "crud-nasabah.jar"]
