version: '3.8'
services:
  app:
    image: crud_nasabah:latest
    build:
      context: .
    container_name: java_springboot
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

    ports:
      - '5433:5432'

  db:
    image: postgres
    container_name: java_spirngboot
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432